version: '3'

services:
  markman:
    build:
      context: .
      dockerfile: docker/Dockerfile-autobuild
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306" # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'markman' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
    volumes:
      - ./data:/var/lib/mysql
