version: '3'

services:
  markman:
    build:
        context: .
        dockerfile: docker/Dockerfile-autobuild
    ports:
      - "8000:8000"

  markman-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3336:3306"